const Tabledata = [
    {
        Prefix: "Mr.",
        Name: "Anthony Yakhni",
        DOB: "10/28/1999",
        category: "Anthony Yakhni",
        Sex:"M",
        Address:"305 Plains Rd e",
        Phone:"905-321-9876",
        FamilyDoc:"Dr. Sonia Mossad",
        BloodType:"B+",
        Ethnicity:"Lebanse",
        Allergies:"N/A",
        Prescriptions:"N/A",
        Notes:"Next Appointment: February26th, 2016",
    },
    {
        Prefix: "Mr.",
        Name: "Anthony",
        DOB: "10/28/1999",
        category: "Anthony Yakhni",
        Sex:"M",
        Address:"305 Plains Rd e",
        Phone:"905-321-9876",
        FamilyDoc:"Dr. Sonia Mossad",
        BloodType:"B+",
        Ethnicity:"Lebanse",
        Allergies:"N/A",
        Prescriptions:"N/A",
        Notes:"Next Appointment: February26th, 2016",
    },
]
export default Tabledata;